# Generated by Django 2.0.5 on 2018-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uri',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
