# Generated by Django 2.0.5 on 2018-06-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180605_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
    ]
