# Generated by Django 2.0.5 on 2018-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20180605_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='scope',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
