# Generated by Django 2.0.3 on 2018-03-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20180325_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
