# Generated by Django 2.0.5 on 2018-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_customuser_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.TextField(blank=True),
        ),
    ]
