# Generated by Django 2.0.3 on 2018-03-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
