# Generated by Django 2.0.5 on 2018-05-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20180325_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
